on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror code to GitLab
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/kingpipe2/Pacman.git'
          GIT_USERNAME: kingpipe2
          GIT_PASSWORD: glpat-ry_wn5ejYiPAZTfRsiA9
